### ISSUE TITLE
Where is the doc

### ISSUE THREAD

**Issue by PopTart-fr** [wieschoo/BotSuite#17]
Hello, 

on botsuite.net the documentation give me an error 404 : www.botsuite.net/documentation/open/build/botsuite401.

So where is the documentation now ?

**Comment by Karill** [comment]
Hello PopTart-fr,

the website was recently completely moved to github. Ir seems that in this process the website structure has at least changed, if not the whole documentation was lost.

I personally do not know where it might be now, but i hope that wieschoo reacts to this issue and can tell you more.

As far as i know the documentation anyway was just extracted from the XML comments of the sourcecode so you could possibly do this yourself if needed. I think Sandcastle was used for that.

**Comment by PopTart-fr** [comment]
Hello Karill,
thanks for answer, any alternative to botsuite ? Because i've try sandscale but i don't have what i want.

**Comment by Karill** [comment]
Hello PopTart-fr,

what are you searching for in the BotSuite? Maybe i am able to help you find the correct classes/methods or an alternative way to solve your problem.

**Comment by PopTart-fr** [comment]
I want to write 2 bot, one is a small bot for a flash game (for learning only) and the second is an automatique stats recorder for hearthstone game like this one : https://github.com/Epix37/Hearthstone-Deck-Tracker

**Comment by Karill** [comment]
So what you are searching for is not the documentation per se but something similar to a tutorial on how to write those bots (or, more generally, bots at all) with the Botsuite, right?

Basically, there are many ways to do that.
The most "easy" way for the flash game might be a simple image/pattern recognition (see class BotSuite.Screenshot and namespace BotSuite.ImageLibrary.*) paired with mouse movement (BotSuite.Mouse) and keyboard actions (BotSuite.Keyboard).

The Stats Recorder you are talking about might not even be a job for the BotSuite. As far as i have seen it just involves reading the logfile(s) of HS and parsing the content. I don't see any possible way the BotSuite might be of use in this scenario, since it is just standard file operations already covered by the .NET Framework itself?!

**Comment by PopTart-fr** [comment]
i've try this : 
    IntPtr hwnd = Window.FindWindowByWindowTitle("Google Chrome");
    Bitmap screen = ScreenShot.CreateFromHidden(hwnd);
    screen.Save("test.bmp");

But not working :s

**Comment by Karill** [comment]
The problem here most likely is that the Window does not have the title "Google Chrome". This occurs because Chrome adds the page title to its own window title (like "New tab - Google Chrome"). The Method you are using does not support that, but there is no alternative.
Your best bet would be to simply make a screenshot of the whole screen instead of just Google Chrome if you can't provide a full title for the BotSuite.

On the other hand, this might be a great enhancement for the BotSuite.
I will implement it today. Be aware that this repository of the BotSuite is now discontinued. I have my "own version" hosted on Bitbucket (bitbucket.org/KarillEndusa/botsuite.net) and will implement it there.

**Comment by PopTart-fr** [comment]
Ok,
 so now the screenshot work but one more time i don't remember how to find matching from my source image (this is why i want the doc ^^ )

**Comment by ViRb3** [comment]
The documentation you're looking for (which is actually comments on methods, fields, properties, etc.) is already included in BotSuite - you just need to explore it. To find an image in the screenshot there are really many ways. I personally like binary patterns since they're the fastest. I'm on mobile right now and can't think source off my head, but I can help you when I get home.

**Comment by wieschoo** [comment]
The documentation was done by
http://sharpdox.de/de/

**Comment by wieschoo** [comment]
I added the documentation again to the botsuite.net webpage.
